# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c0974077-99e1-4ed7-b7c1-18e57a1baa0c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2686fb8d-381b-47e0-8241-045d5c545a39".device = "/dev/disk/by-uuid/2686fb8d-381b-47e0-8241-045d5c545a39";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3FB3-AB64";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/17ade4fe-fdb9-4536-b2f0-dba8dd6d2712"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
